export default {
  CONNECTION_NOT_PROVIDED: 'CONNECTION_NOT_PROVIDED',
  MODEL_NAME_MUST_BE_PROVIDED: 'MODEL_NAME_MUST_BE_PROVIDED',
  RELATION_TABLE_NOT_PROVIDED: 'RELATION_TABLE_NOT_PROVIDED',
  RELATION_COLUMNS_NOT_PROVIDED: 'RELATION_COLUMNS_NOT_PROVIDED',
  INVALID_PARAMS: 'INVALID_PARAMS',
};
